version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    restart: always
